"""updating_models

Revision ID: 542ec916f8c0
Revises: a0349e8420db
Create Date: 2024-03-28 22:44:21.980796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '542ec916f8c0'
down_revision: Union[str, None] = 'a0349e8420db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'sales_employee_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('contracts', 'management_employee_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'contracts', 'employees', ['sales_employee_id'], ['id'])
    op.create_foreign_key(None, 'contracts', 'employees', ['management_employee_id'], ['id'])
    op.add_column('employees', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('password', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.alter_column('events', 'support_employee_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('events', 'management_employee_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint('events_ibfk_1', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'employees', ['management_employee_id'], ['id'])
    op.create_foreign_key(None, 'events', 'contracts', ['contract_id'], ['id'])
    op.create_foreign_key(None, 'events', 'employees', ['support_employee_id'], ['id'])
    op.drop_column('events', 'contrat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('contrat_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_ibfk_1', 'events', 'contracts', ['contrat_id'], ['id'])
    op.alter_column('events', 'management_employee_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('events', 'support_employee_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('events', 'contract_id')
    op.drop_column('employees', 'password')
    op.drop_column('employees', 'email')
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.alter_column('contracts', 'management_employee_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('contracts', 'sales_employee_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
