"""first_migration

Revision ID: b4b4afa14069
Revises: 
Create Date: 2024-04-08 17:47:19.683304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4b4afa14069"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("department", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "department IN ('commercial', 'support', 'gestion')",
            name="valid_department",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone_number", sa.String(length=15), nullable=True),
        sa.Column("company_name", sa.String(length=255), nullable=True),
        sa.Column("created_on", sa.Date(), nullable=True),
        sa.Column("updated_on", sa.Date(), nullable=True),
        sa.Column("sales_employee_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sales_employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contracts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_on", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=255), nullable=True),
        sa.Column("total_amount", sa.Float(), nullable=True),
        sa.Column("left_amount", sa.Float(), nullable=True),
        sa.Column("sales_employee_id", sa.Integer(), nullable=True),
        sa.Column("management_employee_id", sa.Integer(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "status IN ('signed', 'pending', 'cancelled')", name="valid_status"
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["management_employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sales_employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("attendees", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column("support_employee_id", sa.Integer(), nullable=True),
        sa.Column("management_employee_id", sa.Integer(), nullable=True),
        sa.Column("contract_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["management_employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["support_employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    op.drop_table("contracts")
    op.drop_table("clients")
    op.drop_table("employees")
    # ### end Alembic commands ###
